### ISSUE TITLE
Hugo output is lacking content or data

### ISSUE THREAD

**Issue by soypunk** [nboughton/swnt#10]
When using the `--export hugo` flag with command such as `swnt new sector` one would expect the resulting hugo folder to contain the sector content in some form (whether a set of .md files or something in the data directory.) Instead the output is the shell of a hugo site and the correct theme directory but no content. (using the latest versions of go, hugo, and swnt as of this comment posting.)

**Comment by nboughton** [comment]
I'm not able to replicate this. 

```
$ swnt new sector --export hugo
Write Sector? [y]es, [n]o, [r]eroll: [r] y
Exporting as hugo site...
Creating new hugo site...
Congratulations! Your new Hugo site is created in /home/nick/tmp/T'vao Sector/hugo.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.
Initialized empty Git repository in /home/nick/tmp/T'vao Sector/hugo/.git/
Cloning into '/home/nick/tmp/T'vao Sector/hugo/themes/docdock'...
Copying config...
Setting Title...
Copying in default archetype...
Creating Stars dir...
Populating Stars dir...
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Reinocy.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Esiom.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Tihooc.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Ellaide.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Owuneiv.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Stoung.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Iosaivi.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Diemi.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Ytol.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Lehued.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Boucod.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Weng.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Aungea.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Aydioc.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Paub.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Voothath.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Istea.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Ereel.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Vawan.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Iadyd.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Lois.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Lily.md created
/home/nick/tmp/T'vao Sector/hugo/content/Stars/Rytibee.md created
/home/nick/tmp/T'vao Sector/hugo/content/_index.md created
```

**Comment by nboughton** [comment]
![Screenshot from 2020-11-13 09-42-36](https://user-images.githubusercontent.com/8879583/99058134-ae06c980-2594-11eb-9fa5-a45b59e8ce09.png)

**Comment by nboughton** [comment]
```
[nick@gnord hugo]$ go version
go version go1.15.4 linux/amd64
[nick@gnord hugo]$ hugo version
Hugo Static Site Generator v0.78.1/extended linux/amd64 BuildDate: unknown
```

**Comment by soypunk** [comment]
I opened an issue because Jeremy (takeonrules) was seeing the same thing. Perhaps this is a MacOS issue.

    $ go version
    go version go1.15.4 darwin/amd64
    $ hugo version
    Hugo Static Site Generator v0.78.1/extended darwin/amd64 BuildDate: unknown

    $ swnt new sector --export hugo
    Write Sector? [y]es, [n]o, [r]eroll: [r] y
    Exporting as hugo site...
    Creating new hugo site...
    Congratulations! Your new Hugo site is created in /Users/smedero/Desktop/SWN/Anarres Sector/hugo.
    
    Just a few more steps and you're ready to go:

    1. Download a theme into the same-named folder.
        Choose a theme from https://themes.gohugo.io/ or
        create your own with the "hugo new theme <THEMENAME>" command.
    2. Perhaps you want to add some content. You can add single files
        with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
    3. Start the built-in live server via "hugo server".

    Visit https://gohugo.io/ for quickstart guide and full documentation.
    Initialized empty Git repository in /Users/smedero/Desktop/SWN/Anarres Sector/hugo/.git/
    Cloning into '/Users/smedero/Desktop/SWN/Anarres Sector/hugo/themes/docdock'...
    Copying config...
    Setting Title...
    2020/11/13 06:56:14 exit status 1

Let me poke under the hood and see if I can figure out what the content build steps are. Maybe I can add some debug statements to help me figure what's happening.

**Comment by soypunk** [comment]
Probably a MacOS thing. For instance this [line](https://github.com/nboughton/swnt/blob/5aecefbca9dc48dda38ae4bd7178e38457884342/export/hugo.go#L70): in export/hugo.go

	_, err = exec.Command("sed", "-i", fmt.Sprintf("s/TITLE/%s/", h.Name), "config.toml").CombinedOutput()

`sed` on MacOS requires a backup file extension. so this command would look something like: (not tested)

	_, err = exec.Command("sed", "-i",".bak",fmt.Sprintf("s/TITLE/%s/", h.Name), "config.toml").CombinedOutput()

I'll fork your repo and just make some MacOS modifications and see how it goes :-)

**Comment by soypunk** [comment]
Ok, I can confirm with that _one_ line change, hugo export works on MacOS now.

**Comment by soypunk** [comment]
With this line: https://github.com/soypunk/swnt/blob/99cd7f3e97e8ce162608738c8c78b7864ed6008c/export/hugo.go#L70

I now get

    Visit https://gohugo.io/ for quickstart guide and full documentation.
    Initialized empty Git repository in /Users/smedero/Desktop/SWN/Diso Sector/hugo/.git/
    Cloning into '/Users/smedero/Desktop/SWN/Diso Sector/hugo/themes/docdock'...
    Copying config...
    Setting Title...
    Copying in default archetype...
    Creating Stars dir...
    Populating Stars dir...
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Mywhuba.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Doteane.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Siecue.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Ouvawey.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Tinde.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Ainav.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Tauru.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Toon.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Teci.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Orulyl.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Leethul.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Mousei.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Uhuse.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Lipai.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Ymith.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Eetiab.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Leary.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Atilioc.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Ioteytu.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Rieneet.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Mouree.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Noopee.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Mayduney.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Isty.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/Stars/Budupa.md created
    /Users/smedero/Desktop/SWN/Diso Sector/hugo/content/_index.md created
