### ISSUE TITLE
Parameterize sector size

### ISSUE THREAD

**Issue by jeremyf** [nboughton/swnt#5]
As a DIY game master, I want to be able to specify the size of my campaign's sector, so I can expand or contract the size of the sector based on my vision for the campaign.

**Comment by nboughton** [comment]
This is an interesting one. In terms of generating content it's easy to implement. The hard part is in generating the map. I didn't have the time write a proper map generator for the ASCII maps. It's literally just a set template that text is superimposed on (which is also why the library that generates it is called haxcii, it's an awful hack).

**Comment by nboughton** [comment]
I have an idea about template generation that I'm going to have a play with today.

**Comment by nboughton** [comment]
Ok, I've just about finished implementing a template generator for any size sector. I'll commit the new code later today or tomorrow.

**Comment by nboughton** [comment]
New code has been committed. I've set a limit of 99x99 which should be enough for most people.
